Traceback (most recent call last):
  File "./sample.py", line 186, in <module>
    pos0 = h5chain.get_chain()[-1] #continue existing chains...
  File "/nfs/us0/lin/rezacek/emcee3/lib/python3.5/site-packages/emcee-3.0rc2-py3.5.egg/emcee/backends/backend.py", line 72, in get_chain
  File "/nfs/us0/lin/rezacek/emcee3/lib/python3.5/site-packages/emcee-3.0rc2-py3.5.egg/emcee/backends/hdf.py", line 94, in get_value
AttributeError: You must run the sampler with 'store == True' before accessing the results

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./sample.py", line 201, in <module>
    sampler.run_mcmc(pos0, nsteps)
  File "/nfs/us0/lin/rezacek/emcee3/lib/python3.5/site-packages/emcee-3.0rc2-py3.5.egg/emcee/ensemble.py", line 386, in run_mcmc
  File "/nfs/us0/lin/rezacek/emcee3/lib/python3.5/site-packages/emcee-3.0rc2-py3.5.egg/emcee/ensemble.py", line 353, in sample
  File "/nfs/us0/lin/rezacek/emcee3/lib/python3.5/site-packages/emcee-3.0rc2-py3.5.egg/emcee/backends/hdf.py", line 184, in save_step
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/nfs/us0/lin/rezacek/emcee3/lib/python3.5/site-packages/h5py/_hl/dataset.py", line 685, in __setitem__
    selection = sel.select(self.shape, args, dsid=self.id)
  File "/nfs/us0/lin/rezacek/emcee3/lib/python3.5/site-packages/h5py/_hl/selections.py", line 94, in select
    sel[args]
  File "/nfs/us0/lin/rezacek/emcee3/lib/python3.5/site-packages/h5py/_hl/selections.py", line 261, in __getitem__
    start, count, step, scalar = _handle_simple(self.shape,args)
  File "/nfs/us0/lin/rezacek/emcee3/lib/python3.5/site-packages/h5py/_hl/selections.py", line 466, in _handle_simple
    x,y,z = _translate_int(int(arg), length)
  File "/nfs/us0/lin/rezacek/emcee3/lib/python3.5/site-packages/h5py/_hl/selections.py", line 486, in _translate_int
    raise ValueError("Index (%s) out of range (0-%s)" % (exp, length-1))
ValueError: Index (1002) out of range (0-1001)
